// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrCb1yaJU23nVjE5lRWvSe7eGPozVr8YY',
    appId: '1:283533741353:web:a970f5599eb6d9ea02fb38',
    messagingSenderId: '283533741353',
    projectId: 'night-market-9d893',
    authDomain: 'night-market-9d893.firebaseapp.com',
    storageBucket: 'night-market-9d893.firebasestorage.app',
    measurementId: 'G-D2QH9YRE18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEtuX6yZyZoNLpECF9ob1m0voLQ8fkhWs',
    appId: '1:283533741353:android:f6fd16e515153b7102fb38',
    messagingSenderId: '283533741353',
    projectId: 'night-market-9d893',
    storageBucket: 'night-market-9d893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgqlQIL5jujHIpF5YVZXyuRRKhicxbmCk',
    appId: '1:283533741353:ios:8651767bff54ed7b02fb38',
    messagingSenderId: '283533741353',
    projectId: 'night-market-9d893',
    storageBucket: 'night-market-9d893.firebasestorage.app',
    iosClientId: '283533741353-voko9pu5nchmqeel2pjut3m1psrh1mf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.nightMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgqlQIL5jujHIpF5YVZXyuRRKhicxbmCk',
    appId: '1:283533741353:ios:8651767bff54ed7b02fb38',
    messagingSenderId: '283533741353',
    projectId: 'night-market-9d893',
    storageBucket: 'night-market-9d893.firebasestorage.app',
    iosClientId: '283533741353-voko9pu5nchmqeel2pjut3m1psrh1mf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.nightMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrCb1yaJU23nVjE5lRWvSe7eGPozVr8YY',
    appId: '1:283533741353:web:966d7810f99545ce02fb38',
    messagingSenderId: '283533741353',
    projectId: 'night-market-9d893',
    authDomain: 'night-market-9d893.firebaseapp.com',
    storageBucket: 'night-market-9d893.firebasestorage.app',
    measurementId: 'G-FPB0FFLBP3',
  );
}
